import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Typewriter from 'typewriter-effect'

import {BsArrowRight,BsDash,BsCloudDownload} from 'react-icons/bs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const identification = ['a developer', 'a designer', 'an idea builder', 'a problem solver', 'a programmer' , 'a curious technologist', 'a tech enthusiast', 'a lifelong learner']

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.head}>
          {/* I am a developer, designer, and writer, an idea builder and a problem solver, a maker and a doer. I am a creative technologist, a digital artist, and a digital storyteller. I am a digital nomad, a world traveler, and a lifelong learner. I am a husband, a father, and a friend. I am a human being. */}
          <h1 className={styles.title}>
            I am &nbsp;
            <div className={styles.typewriter}>
            <Typewriter
              options={{
                strings: identification,
                autoStart: true,
                loop: true,
              }}
            />
            </div>
          </h1>
                 {/* ! add arrow button and know more link linking to about page  */}
          {/* <button className={styles.resume}> */}
          <a href="/about" className={styles.more}><BsDash/>More about me<BsArrowRight className={styles.move}/></a>
            {/* {/* <a href="/about" className={styles.resume}>RESUME</a> */}
            <a href="https://drive.google.com/file/d/16fm7VKzE4XsoOghdVg8QcoA0kLYtjWhp/view?usp=sharing" target="_blank" className={styles.resume}><BsCloudDownload/>&nbsp; RESUME</a> 
          {/* </button> */}
        </section>
      </main>
    </>
  )
}
