import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Typewriter from 'typewriter-effect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const identification = ['a developer', 'a designer', 'a writer', 'an idea builder', 'a problem solver', 'a maker', 'a doer', 'a creative technologist', 'a lifelong learner']

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.head}>
          {/* I am a developer, designer, and writer, an idea builder and a problem solver, a maker and a doer. I am a creative technologist, a digital artist, and a digital storyteller. I am a digital nomad, a world traveler, and a lifelong learner. I am a husband, a father, and a friend. I am a human being. */}
          <h1 className={styles.title}>
            I am &nbsp;
            <span className={styles.typewriter}>
            <Typewriter
              options={{
                strings: identification,
                autoStart: true,
                loop: true,
              }}
            />
            </span>
          </h1>
          <svg width="365px" height="372px" viewBox="0 0 365 372" version="1.1" xmlns="http://www.w3.org/2000/svg">
            <path d="M178.746 371C281.059 371 364 288.173 364 186S328.634 1 178.746 1C28.857 1 65.06 129 24.004 186c-76.087 105.633 52.429 185 154.742 185z" stroke="#EA607E" fill="none" fillRule="evenodd"></path>
          </svg>
          
        </section>
      </main>
    </>
  )
}
